spring:
  application:
    name: chii-piyo

  # PostgreSQLへの接続設定
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    # マイグレーションSQLを探すパス
    locations: classpath:db/migration
    # 既存DBにFlywayを後付けするかの設定 ※初期構築のためOFF設定
    baseline-on-migrate: false
    # 過去のバージョン番号を持つファイルの追加実行を許可するか
    out-of-order: false
    # 実行済みのSQLファイルが以前実行した時と同じ内容であるかをチェック
    validate-on-migrate: true

  # Spring Securityの設定
  security:
    oauth2:
      resourceserver:
        jwt:
          # JWTの発行元を検証するための設定
          issuer-uri: ${COGNITO_ISSUER}
          # Spring Bootは起動時にOIDC Discoveryエンドポイントを叩いてJWKをキャッシュしようとするが、CognitoはOIDC Discoveryに完全準拠していない部分があるのでjwk-set-uriも明示的に指定
          jwk-set-uri: ${COGNITO_JWKS_URI}

  # 非同期処理のスレッドプール設定
  task:
    execution:
      pool:
        # コアスレッド数と最大スレッド数を同じにして、キューにタスクを溜める方式にする
        # 1スレッドが埋まった後の処理依頼はキューで待機して順次実行される
        # 親族内利用想定でコスト面からサーバースペックも限られている、かつ多少の遅延は許容されるためこの設定にする
        core-size: 1
        max-size: 1
        queue-capacity: 100

aws:
  # Cognitoの設定
  cognito:
    audience: ${COGNITO_CLIENT_ID}
  # s3の設定
  s3:
    region: ap-northeast-1
    bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY_ID}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY}

# サムネイル生成の設定
thumbnail:
  # サムネイルの最大辺のピクセル数
  max-edge-pixels: 400
  # JPEGの品質 (0.0 - 1.0)
  jpeg-quality: 0.85
  # 動画のサムネイルを生成する際のフレーム位置 (秒)
  video-frame-second: 1
  # ffmpegの実行パス
  ffmpeg-path: ${FFMPEG_PATH:ffmpeg}
  # サムネイル生成のリトライ間隔（ミリ秒）
  retry-interval-ms: 86400000  # 24時間
  # サムネイル生成の際に処理するメディアファイルの最大サイズ（バイト単位）
  # 境界値事故防止のため、フロント指定より少し大きめに設定
  max-image-bytes: 22020096  # 21MB
  max-video-bytes: 110100480  # 105MB

# アプリケーションの管理エンドポイントの設定
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# CORS設定
app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
  # 初期管理者メールアドレス ※未設定の場合は空文字
  admin-email: ${ADMIN_EMAIL:}

server:
  servlet:
    context-path: /api/v1
